esphome:
  name: hasstate
  platform: ESP32
  board: esp-wrover-kit
external_components:
  - source: components

wifi:
  networks:
    - ssid: "MySSID"
      password: "password1"

text_sensor:
  - platform: wifi_info
    scan_results:
      name: "Scan Results"
      id: scan_results
  - platform: version
    name: "ESPHome Version No Timestamp"
    id: version_string
    hide_timestamp: True

binary_sensor:
  - platform: group_has_state
    id: ready
    sensors:
      - scan_results
      - version_string
